export const gridData = [
    {
        campaign_name: 'retargeting campaign 1',
        campaign_id: '23854594149590431',
        daily_budget: 86,
        status: 'PENDING',
        campaign_placement: ['facebook'],
        user_id: '643fa76ff0ed0bf6ab0c2c82',
        shop_id: 902,
        start_date: '04/28/2023',
        end_date: '05/01/2023',
        spend: 0,
        impressions: 0,
        clicks: 0,
        orders: 0,
        sales: 0,
        roas: 0,
    },
    {
        campaign_name: 'retargeting campaign 2',
        campaign_id: '23854594149590432',
        daily_budget: 86,
        status: 'PAUSED',
        campaign_placement: ['facebook'],
        user_id: '643fa76ff0ed0bf6ab0c2c82',
        shop_id: 902,
        start_date: '04/28/2023',
        end_date: '',
        spend: 0,
        impressions: 0,
        clicks: 0,
        orders: 0,
        sales: 0,
        roas: 0,
    },
    {
        campaign_name: 'retargeting campaign 3',
        campaign_id: '23854594149590433',
        daily_budget: 86,
        status: 'ERRORS',
        campaign_placement: ['facebook'],
        user_id: '643fa76ff0ed0bf6ab0c2c82',
        shop_id: 902,
        start_date: '04/28/2023',
        end_date: '05/01/2023',
        spend: 0,
        impressions: 0,
        clicks: 0,
        orders: 0,
        sales: 0,
        roas: 0,
    },
    {
        campaign_name: 'retargeting campaign 4',
        campaign_id: '23854594149590434',
        daily_budget: 86,
        status: 'SCHEDULED',
        campaign_placement: ['facebook'],
        user_id: '643fa76ff0ed0bf6ab0c2c82',
        shop_id: 902,
        start_date: '04/28/2023',
        end_date: '05/01/2023',
        spend: 0,
        impressions: 0,
        clicks: 0,
        orders: 0,
        sales: 0,
        roas: 0,
    },
    {
        campaign_name: 'retargeting campaign 5',
        campaign_id: '23854594149590435',
        daily_budget: 86,
        status: 'ACTIVE',
        campaign_placement: ['facebook', 'instagram'],
        user_id: '643fa76ff0ed0bf6ab0c2c82',
        shop_id: 902,
        start_date: '04/28/2023',
        end_date: '',
        spend: 0,
        impressions: 0,
        clicks: 0,
        orders: 0,
        sales: 0,
        roas: 0,
    },
    {
        campaign_name: 'retargeting campaign 6',
        campaign_id: '23854594149590436',
        daily_budget: 86,
        status: 'ENDED',
        campaign_placement: ['instagram'],
        user_id: '643fa76ff0ed0bf6ab0c2c82',
        shop_id: 902,
        start_date: '04/28/2023',
        end_date: '05/01/2023',
        spend: 0,
        impressions: 0,
        clicks: 0,
        orders: 0,
        sales: 0,
        roas: 0,
    },
];

export const gridHead = [
    {
        dataIndex: 'campaign_name',
        fixed: 'left',
        key: 'campaign_name',
        title: 'Campaign',
    },
    {
        dataIndex: 'statusComponent',
        fixed: 'left',
        key: 'status',
        title: 'Status',
    },
    {
        dataIndex: 'campaign_placement',
        key: 'campaign_placement',
        title: 'Placement',
    },
    { dataIndex: 'start_date', key: 'start_date', title: 'Start Date' },
    { dataIndex: 'end_date', key: 'end_date', title: 'End Date' },
    {
        dataIndex: 'daily_budget',
        key: 'daily_budget',
        title: 'Daily Budget',
    },
    { dataIndex: 'spend', key: 'spend', title: 'Spend' },
    { dataIndex: 'sales', key: 'sales', title: 'Sales' },
];

export const pageArr = [
    {
        label: '5',
        value: '5',
    },
    {
        label: '10',
        value: '10',
    },
    {
        label: '15',
        value: '15',
    },
    {
        label: '20',
        value: '20',
    },
    {
        label: '25',
        value: '25',
    },
];

export const newColumns = [
    {
        dataIndex: 'impressions',
        key: 'impressions',
        title: 'Impressions',
        checked: false,
    },
    { dataIndex: 'clicks', key: 'clicks', title: 'Clicks', checked: false },
    { dataIndex: 'orders', key: 'orders', title: 'Orders', checked: false },
    { dataIndex: 'roas', key: 'roas', title: 'ROAS', checked: false },
];

export const filterVal = [
    { status: 'Archived', checked: false },
    { status: 'Active', checked: false },
    { status: 'Disconnected', checked: false },
    { status: 'Ended', checked: false },
    { status: 'Error', checked: false },
    { status: 'Paused', checked: false },
    { status: 'Pending', checked: false },
    { status: 'Scheduled', checked: false },
];
